# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hazard_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 471)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calculate_TV = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_TV.setGeometry(QtCore.QRect(20, 20, 71, 32))
        self.calculate_TV.setObjectName("calculate_TV")
        self.calculate_hazard_base = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_hazard_base.setGeometry(QtCore.QRect(110, 20, 101, 32))
        self.calculate_hazard_base.setObjectName("calculate_hazard_base")
        self.calculate_hazard_benchmark = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_hazard_benchmark.setGeometry(QtCore.QRect(230, 20, 141, 32))
        self.calculate_hazard_benchmark.setObjectName("calculate_hazard_benchmark")
        self.plot_hazard_slide = QtWidgets.QPushButton(self.centralwidget)
        self.plot_hazard_slide.setGeometry(QtCore.QRect(390, 20, 113, 32))
        self.plot_hazard_slide.setObjectName("plot_hazard_slide")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuCalculate = QtWidgets.QMenu(self.menubar)
        self.menuCalculate.setObjectName("menuCalculate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Trade = QtWidgets.QAction(MainWindow)
        self.actionLoad_Trade.setObjectName("actionLoad_Trade")
        self.actionLoad_Model = QtWidgets.QAction(MainWindow)
        self.actionLoad_Model.setObjectName("actionLoad_Model")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionTV = QtWidgets.QAction(MainWindow)
        self.actionTV.setObjectName("actionTV")
        self.actionHazard_Risk = QtWidgets.QAction(MainWindow)
        self.actionHazard_Risk.setObjectName("actionHazard_Risk")
        self.actionHazard_Benchmark = QtWidgets.QAction(MainWindow)
        self.actionHazard_Benchmark.setObjectName("actionHazard_Benchmark")
        self.actionHazard_Slide = QtWidgets.QAction(MainWindow)
        self.actionHazard_Slide.setObjectName("actionHazard_Slide")
        self.menuOpen.addAction(self.actionLoad_Trade)
        self.menuOpen.addAction(self.actionLoad_Model)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuCalculate.addAction(self.actionTV)
        self.menuCalculate.addSeparator()
        self.menuCalculate.addAction(self.actionHazard_Risk)
        self.menuCalculate.addAction(self.actionHazard_Benchmark)
        self.menuCalculate.addAction(self.actionHazard_Slide)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalculate.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculate_TV.setText(_translate("MainWindow", "TV"))
        self.calculate_hazard_base.setText(_translate("MainWindow", "Hazard Risk"))
        self.calculate_hazard_benchmark.setText(_translate("MainWindow", "Hazard Benchmark"))
        self.plot_hazard_slide.setText(_translate("MainWindow", "Hazard Slide"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuCalculate.setTitle(_translate("MainWindow", "Test"))
        self.actionLoad_Trade.setText(_translate("MainWindow", "Load Trade"))
        self.actionLoad_Model.setText(_translate("MainWindow", "Load Model"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionTV.setText(_translate("MainWindow", "TV"))
        self.actionHazard_Risk.setText(_translate("MainWindow", "Hazard Risk"))
        self.actionHazard_Benchmark.setText(_translate("MainWindow", "Hazard Benchmark"))
        self.actionHazard_Slide.setText(_translate("MainWindow", "Hazard Slide"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
